// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Desktop: typeof import('./components/Header/Desktop.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeaderLabel: typeof import('./components/Header/HeaderLabel.vue')['default']
    HeaderNavigationDesktop: typeof import('./components/Header/HeaderNavigationDesktop.vue')['default']
    HeaderNavigationMobile: typeof import('./components/Header/HeaderNavigationMobile.vue')['default']
    Mobile: typeof import('./components/Header/Mobile.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
